### PR TITLE
Added low quantity field as a optional field for add command

### LINKED ISSUE #185: Add low quantity field to add command

### PR DESCRIPTION
**Pull request by Ashley-Lau**
Test cases for add command and quantity updated as well

### CODE REVIEW

**Comment by Ashley-Lau** [comment]
Included changes for print command here as i dont want to make another pr before this branch is merged.

**Comment by LimZeWeiDennis** [comment]
LGTM!

**Review by LimZeWeiDennis — COMMENTED** [review]
LGTM

**Review by LimZeWeiDennis — APPROVED** [review]
LGTM

**Pull request merged**
